IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'IMPORT_PROTIME_AFWEZIGHEDEN')
BEGIN
    CREATE TABLE IMPORT_PROTIME_AFWEZIGHEDEN (
        EMPLID nvarchar(255) NULL,
        ABS_DATE nvarchar(255) NULL,
        DURATION nvarchar(255) NULL,
        ABSENCE_CODE nvarchar(255) NULL,
        IMPORT_DATE datetime NULL,
        EMPNR_PROTIME nvarchar(255) NULL
    );
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_TRUNCATEIMPORTTABLE]') AND type IN (N'P', N'PC'))
BEGIN
    CREATE PROCEDURE SP_TRUNCATEIMPORTTABLE AS
    SELECT * FROM [dbo].[IMPORT_PROTIME_AFWEZIGHEDEN];
END

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_SYNCAFWEZIGHEID]') AND type IN (N'P', N'PC'))
BEGIN
    CREATE PROCEDURE SP_SYNCAFWEZIGHEID AS
    SELECT * FROM [dbo].[IMPORT_PROTIME_AFWEZIGHEDEN];
END
